theme: poison
title: subtlepseudonym

languageCode: en-us
enableRobotsTXT: true

paginate: 5
pluralizelisttitles: false

params:
  brand: Connor Demille
  brand_image: /images/lemon_square_small.jpg
  description: Maker, Engineer, Hobbyist
  dark_mode: true

  menu:
    - Name: Articles
      URL: /articles/
      HasChildren: true
      Limit: 0
    - Name: Projects
      URL: /projects/
      HasChildren: false
    - Name: About
      URL: /about/
      HasChildren: false

  github_url: https://github.com/subtlepseudonym
  kofi_url: https://ko-fi.com/subtlepseudonym
  linkedin_url: https://www.linkedin.com/in/subtlepseudonym
  mastodon_url: https://mastodon.sdf.org/@subtlepseudonym
  medium_url: https://subtlepseudonym.medium.com


taxonomies:
  series: series
